# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectsTestsQuestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatarImages/')),
                ('gender', models.CharField(max_length=5)),
                ('dateOfBirth', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('placeOfWorkOrStudy', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=50)),
                ('motivationMessage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CF_max', models.IntegerField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.applyApplication')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('applyApp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.applyApplication')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Project')),
            ],
        ),
        migrations.CreateModel(
            name='testsApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('applyApp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.applyApplication')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Subject')),
                ('tests_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Test')),
            ],
        ),
    ]
