# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyapplication',
            name='behanceLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='applyapplication',
            name='faceBookLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='applyapplication',
            name='googlePlusLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='applyapplication',
            name='instagrammLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='applyapplication',
            name='linkedInLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='applyapplication',
            name='skypeLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='applyapplication',
            name='telegrammLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='applyapplication',
            name='twitterLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
