# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0015_auto_20160526_1840'),
        ('apply', '0002_testsapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Project')),
                ('applyApp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.applyApplication')),
            ],
        ),
    ]
