# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-26 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_projectpriority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpriority',
            old_name='Project_id',
            new_name='project_id',
        ),
    ]
