# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-26 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0017_auto_20160526_1916'),
        ('apply', '0004_auto_20160526_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsapply',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Subject'),
        ),
    ]
