# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_destribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsapply',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Subject'),
        ),
    ]
