# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-03 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_auto_20160528_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyapplication',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatarImages/'),
        ),
    ]
