# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0011_auto_20160603_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyapplication',
            name='image',
            field=models.ImageField(default='/avatarImages/qa.png', upload_to='avatarImages/'),
        ),
    ]
