# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-03 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0012_auto_20160603_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyapplication',
            name='image',
            field=models.ImageField(upload_to='avatarImages/'),
        ),
    ]
