# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-05 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0014_auto_20160605_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyapplication',
            name='image',
            field=models.ImageField(upload_to='avatarImages/'),
        ),
    ]
