# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 10:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160504_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_paragraph',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
