# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 11:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170421_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_paragraph',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
