# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 13:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkForEachProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='projectImages/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('mentor_image', models.ImageField(blank=True, upload_to='projectMentorImages/')),
                ('mentor_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('minMembers', models.IntegerField()),
                ('maxMembers', models.IntegerField()),
                ('members', models.ManyToManyField(blank=True, related_name='_project_members_+', to=settings.AUTH_USER_MODEL)),
                ('mentor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='newsForCurrentProjectImages/')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectnews', to='projectsTestsQuestions.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('right_answer', models.CharField(max_length=50)),
                ('wrong_answer1', models.CharField(max_length=50)),
                ('wrong_answer2', models.CharField(max_length=50)),
                ('wrong_answer3', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='markforeachproject',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Project'),
        ),
        migrations.AddField(
            model_name='markforeachproject',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Subject'),
        ),
    ]
