# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
