# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-18 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0002_project_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_news',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
