# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0003_auto_20170518_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projectImages/'),
        ),
    ]
