# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-06 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0004_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='tests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Tests'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='members',
            field=models.ManyToManyField(related_name='_projects_members_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
