# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-06 22:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectsTestsQuestions', '0005_auto_20160506_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('members', models.ManyToManyField(related_name='_project_members_+', to=settings.AUTH_USER_MODEL)),
                ('mentor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='members',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='mentor_id',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
