# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0006_auto_20160506_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tests',
        ),
        migrations.AddField(
            model_name='test',
            name='wrong_answer1',
            field=models.CharField(default='should be wrong value', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='wrong_answer2',
            field=models.CharField(default='should be wrong value', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='wrong_answer3',
            field=models.CharField(default='should be wrong value', max_length=50),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
