# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0007_auto_20160521_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='wrong_answer1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='wrong_answer2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='wrong_answer3',
            field=models.CharField(max_length=50),
        ),
    ]
