# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-24 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0008_auto_20160521_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projectImages/'),
        ),
        migrations.AddField(
            model_name='project',
            name='mentorImage',
            field=models.ImageField(blank=True, upload_to='projectMentorImages/'),
        ),
    ]
