# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0009_auto_20160524_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=300),
        ),
    ]
