# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0012_auto_20160525_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mentor_description',
            field=models.TextField(),
        ),
    ]
