# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-26 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0013_auto_20160525_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkForEachProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Project')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Subject')),
            ],
        ),
    ]
