# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0014_markforeachproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markforeachproject',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
