# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-05-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0015_auto_20160526_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='maxMembers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='minMembers',
            field=models.IntegerField(default=0),
        ),
    ]
