# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 11:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0018_project_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
