# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 09:26
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsTestsQuestions', '0019_auto_20170425_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
