# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afterSchool', '0002_auto_20170527_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectsTestsQuestions.Project'),
        ),
        migrations.AlterField(
            model_name='reportproject',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
