# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 13:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apply', '0002_auto_20170516_2043'),
        ('afterSchool', '0003_auto_20170527_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 5, 28, 13, 54, 44, 766944, tzinfo=utc))),
                ('applyApp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.applyApplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reportproject',
            name='comment',
            field=models.ManyToManyField(blank=True, to='afterSchool.reportComments'),
        ),
    ]
