# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170515_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 15, 15, 59, 8, 716989, tzinfo=utc)),
        ),
    ]
