# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20170523_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 23, 11, 25, 30, 670955, tzinfo=utc)),
        ),
    ]
