# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20170516_2043'),
        ('chat', '0018_auto_20170524_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 13, 51, 55, 614953, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='room',
            name='membersApplyApp',
        ),
        migrations.AddField(
            model_name='room',
            name='membersApplyApp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apply.applyApplication'),
        ),
    ]
