# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 15:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20170524_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 15, 2, 12, 23755, tzinfo=utc)),
        ),
    ]
