# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20170516_2043'),
        ('chat', '0031_auto_20170531_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 21, 37, 32, 768652, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='room',
            name='membersApplyApp',
        ),
        migrations.AddField(
            model_name='room',
            name='membersApplyApp',
            field=models.ManyToManyField(blank=True, null=True, to='apply.applyApplication'),
        ),
    ]
