# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_auto_20170531_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 12, 4, 58, 308505, tzinfo=utc)),
        ),
    ]
