# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='aboutUs/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
